# Generated by Django 5.2.8 on 2025-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='units_donated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
